version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/weblog
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=elasticsearch
      - DEV_DATABASE_HOST=db
    depends_on:
      - db
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     # - xpack.security.enabled=false
  #     # - xpack.monitoring.enabled=false
  #     # - xpack.graph.enabled=false
  #     # - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .:/weblog
    ports:
      - "9200:9200"
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.5.1
  #   environment:
  #     SERVER_NAME: localhost
  #     ELASTICSEARCH_URL: http://localhost:9200/
  #   ports:
  #     - 5601:5601
  #   volumes:
  #     - .:/weblog
  #   ulimits:
  #     nproc: 65535
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   cap_add:
  #     - ALL